generatorName: typescript-fetch
inputSpec: ./openapi.json
outputDir: src/generated
templateDir: ./openapi-templates
additionalProperties:
  supportsES6: true
  typescriptThreePlus: true
  useSingleRequestParameter: true
  withInterfaces: true
  useTags: false
globalProperties:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false
